### ISSUE TITLE
Higher OpenWrt Release support

### ISSUE THREAD

**Issue by MaStr** [PirateBox-Dev/PirateBoxScripts_Webserver#142]
Currently the complete PirateBox is only working against AA release of OpenWrt.

We should target to update the support against ChaosCalmer

**Comment by MaStr** [comment]
Things ToDo:

- With  ChaosCalmer, lighttpd is started after package installation. Stop & disable lighttpd during installation of PirateBox package like uhttpd

**Comment by nl-meduza** [comment]
Complete putty log from [this](https://forum.piratebox.cc/read.php?22,19523,19594#msg-19594) input, [putty20160430_222410_meduza.txt](https://github.com/PirateBox-Dev/PirateBoxScripts_Webserver/files/245908/putty20160430_222410_meduza.txt):

- When running '/etc/init.d/piratebox start' the following line is printed:
`losetup: /dev/loop0: detach failed: No such device or address`. (_line 712_)
Look's like false positive error message ([forum post](https://forum.piratebox.cc/read.php?22,19523,19593#msg-19593)) Suppress message?
- When running '/etc/init.d/piratebox start' the following lines are printed:
`Empty tmp folder` and
`rm: '/opt/piratebox/tmp' is a directory` (_line 718_)
Is there a real purpose for removing the complete tmp directory or is emptying the content within enough?
- During install of the piratebox-mod-imageboard the following line is printed:
`Command failed: Not found` (_line 545_)
I have no clue yet what command is causing this message.
- During install of the piratebox-mod-imageboard the following line is printed:
`wget: can't connect to remote host (127.0.0.1): Connection refused` (_line 680_)
This is because the piratebox script is 'Stopping lighttpd...' Suppress message?

Food for thought:
- Is `sed -i 's|DROOPY_USE_USER="no"|DROOPY_USE_USER="yes"|g' /opt/piratebox/conf/piratebox.conf` still needed? Without the upload works as well. (for me. please verify)
- Clear up confusion about Timesave function ([link](http://piratebox.aod-rpg.de/dokuwiki/doku.php/openwrt/extroot?s[]=vocore#piratebox_post-installation)). Enable this function or not when running on ChaosCalmer?

**Comment by MaStr** [comment]
I think updating firewall & network config can omitted too, because we always advice a reboot

**Comment by MaStr** [comment]
Started to work on this.

* Changed dependency on PHP5 packages.
* radvd is now in oldpackages => Dependency needs to be removed and disconfigured for OpenWRT. Need to make system config changes to advertise IPV6 correctly - maybe.

On LibraryBox - proftpd went to oldpackages and can't be supported by the current mechanism... as we try to avoid to add binary files , @griffey

**Comment by MaStr** [comment]
Repositories are now separated by package source after build:

```
$ ls bin/ar71xx/packages/
base/        luci/        management/  oldpackages/ packages/    piratebox/   routing/     telephony/
$ ls bin/ar71xx/packages/piratebox/
box-installer_2.1.3-1_all.ipk            Packages.gz
extendRoot_0.10.1-3_all.ipk              Packages.sig
extendRoot-dbus_0.10.1-3_all.ipk         pbxmesh_1.1.2-2_all.ipk
extendRoot-lighttpd_0.10.1-3_all.ipk     pbxopkg_0.1.1-1_all.ipk
extendRoot-php_0.10.1-3_all.ipk          pbxopkg-beta_0.1.1-1_all.ipk
extendRoot-php-fastcgi_0.10.1-3_all.ipk  piratebox_1.2.0-1_all.ipk
extendRoot-proftpd_0.10.1-3_all.ipk      piratebox-mod-imageboard_1.2.0-1_all.ipk
extendRoot-python_0.10.1-3_all.ipk       usb-config-scripts_0.4.2-7_all.ipk
extendRoot-zoneinfo_0.10.1-3_all.ipk     usb-config-scripts-librarybox_0.4.2-7_all.ipk
Packages

```

**Comment by MaStr** [comment]
ok. Done for today.

https://github.com/PirateBox-Dev/openwrt-piratebox-feed/tree/CC_adjustments
https://github.com/PirateBox-Dev/openwrt-piratebox-feed/tree/CC_adjustments

It is possible to move from a dbus avahi version to nondbus. That removes a some of the complexity.

 I am stuck at recursive dependency errors from the openwrt built

```
Collecting package info: done
tmp/.config-package.in:22173:error: recursive dependency detected!
tmp/.config-package.in:22173:	symbol PACKAGE_extendRoot-librarybox depends on PACKAGE_avahi-nodbus-daemon
tmp/.config-package.in:18014:	symbol PACKAGE_avahi-nodbus-daemon is selected by PACKAGE_extendRoot-avahi
tmp/.config-package.in:22149:	symbol PACKAGE_extendRoot-avahi is selected by PACKAGE_extendRoot-librarybox
tmp/.config-package.in:12071:error: recursive dependency detected!
tmp/.config-package.in:12071:	symbol PACKAGE_php5 is selected by PACKAGE_extendRoot-php
tmp/.config-package.in:22231:	symbol PACKAGE_extendRoot-php is selected by PACKAGE_extendRoot-piratebox
tmp/.config-package.in:22280:	symbol PACKAGE_extendRoot-piratebox depends on PACKAGE_php5
configuration written to .config
```

When I try to fix it, I get other weird dependency issues - with and without error message.

It is needed to manually activate some packages to get all options in openwrt menuconfig.. trying to find a solution.  https://wiki.openwrt.org/doc/devel/packages

**Comment by MaStr** [comment]
Done, development branch is now working on LEDE 17.01.2
