### ISSUE TITLE
Lock shoutbox until POST of chatline comes back.

### ISSUE THREAD

**Issue by MaStr** [PirateBox-Dev/PirateBoxScripts_Webserver#67]
refers to: http://forum.piratebox.cc/read.php?2,5919,11821#msg-11821

Shoutbox gives not enough feedback in case of the PirateBox take more time to process the posting of the message.

**Comment by miketweaver** [comment]
I was thinking about this. What if you just had the post_shoutbox function call refresh_shoutbox at the end of it? 
https://github.com/PirateBox-Dev/PirateBoxScripts_Webserver/blob/master/piratebox/piratebox/www/scripts.js#L107-L113

That what the user who sends the chat message sees it on their screen immediately, instead of waiting for the ajax to refresh it.

**Comment by MaStr** [comment]
I'm not sure if that helps. The post function gets a callback function assigned which actually does the refresh. While writing about it, I come to the conclusion, that it already should work like exepected- but it doesn't?! Or am I understanding the part of the JS wrong?

It seems in some cases it still runs asynchronous .. mh

**Comment by miketweaver** [comment]
Well, in my testing yesterday I noticed that I would type a chat message and it wouldn't appear for 20ish seconds or so. To the point where other clients would have the chat message appear on their screen even before it appeared on the sender's screen. I'll do some additional testing and see what I find.

**Comment by deavmi** [comment]
Would this then stop spamming well for some split seconds.
